### ISSUE TITLE
Code splitting bundle segregation for theming

### ISSUE THREAD

**Issue by cwalten** [cerner/terra-toolkit#200]
# Future Functionality Discussion

## Description
When working on a code splitting project, an issue was run across where dynamically imported bundles were not themed correctly in certain browsers. This is likely due to older browsers not being able to dynamically apply CSS variables when imported. As such, some items do not receive correct theming if they are included in a bundle that got imported after static variable application.

This is avoidable by creating a wrapping entrypoint which specifically pulls in the theme code. However, this is not scalable when multiple themes are involved (one entrypoint and container logic per theme).

## Additional Context / Screenshots
There was some discussion of a webpack plugin injecting theme code into each bundle. Not sure the specifics on that, but as a starting point, it makes sense.

## @ Mentions
@mjhenkes @tbiethman @bjankord @ryanthemanuel

**Comment by bjankord** [comment]
My understanding of this issue is that as the code is split into chunks, the themable variables make it into only 1 chunk. Then as postcss is run, only that one chunk gets the processed CSS custom properties that are needed to work in IE. The other code split chunks have CSS, but don't have the CSS custom properties defined in their chunk and so when postcss processes the CSS, it does so without the theme applied to that chunk.

@mhemesath has explored using https://github.com/jhildenbiddle/css-vars-ponyfill which I think may be a solution for this use-case. If you team needs to code-split, instead of running postcss-custom-properties which causes the issue of the theme code only being pulled into 1 code split bundle/chunk, don't run postcss and instead leave the application of the CSS custom properties in IE up to https://github.com/jhildenbiddle/css-vars-ponyfill.

Edit: This is only an idea, would need to be tested to see if it resolves the issue your team saw @cwalten

**Comment by ryanthemanuel** [comment]
@cwalten I have a potential fix for this that I'm working on.

**Comment by cwalten** [comment]
@ryanthemanuel I was informed earlier today. Please let me know if we can try something out to help.
