### ISSUE TITLE
Perform accessibility tests when taking screenshots

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-toolkit#249]
# Feature Request

## Description

In order to better support and require accessibility, we will create a mechanism to perform accessibility testing whenever a screenshot is captured.

## Design
After discussing these changes with a few people there are a few assumptions I want to make about how this will work.

- This will be a new helper method that wraps both screenshot comparisons and accessibility.  Unfortunately this will mean that teams won't get this for free but this will allow us to make the change non-passively and without any additional configuration.
- Multiple form factors *will not* be supported with a single call to this new method helper.  This is the direction that we want to go with our tests.  It is more efficient and in the cases where we can parallelize all of our form factors, this way of executing tests is not compatible.  
- Selectors *will* be supported.  Any selector being used for screenshots will also be used for accessibility.
- Other configurations will be supported as well.  The method signature will be the same as the existing screenshot method except axe options will now be accepted in the options hash.

**Comment by bjankord** [comment]
I'm good with this. I'd like to keep the existing methods for accessibility for teams that are wanting to do accessibility tests without visual regression tests.

**Comment by emilyrohrbough** [comment]
We should also strip out the `viewportChangePause` option in this new method. This value would never be used since viewports will not be accepted.

I would also like to remove the runOnly axe option from this method. This allows the a11y tags to be defined for that particular test run and IMO we should be defining this one time at the root configuration level, not a test-by-test basis.

In my head the API would be: (with a WAY better name)
```
Terra.should.checkItAll('optional_screenshot_name', {
    selector: '' // for both VR & axe
    misMatchTolerance: '' // mismatch tolerance value if different than default <-- also do we even want this?
    rules: [] // axe rules
});
```

Then, IMO we should check accessibility first, then screenshot comparison. I think it would fail faster if this were to fail.
