### ISSUE TITLE
Add an Environment Variable for bail in the wdio config

### ISSUE THREAD

**Issue by revoyrm** [cerner/terra-toolkit#267]
# Feature Request

## Description
I want to be able to have the wdio tests stop running after a failure so I can see the error message without having to run the whole test suite.

## Additional Context / Screenshots
I talked about this with Matt Henkes in your Teams channel. And I found a way to do it by overriding the values in your config with 
```
bail: 1,
mochaOpts: {
    bail: true,
 },
```

but Matt wanted me to log an issue here to get an environment variable for it

[Here](https://teams.microsoft.com/l/message/19:c6dba7aa664b49b68984612c69457ac0@thread.skype/1553526188905?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1553526188905&teamName=Terra&channelName=General&createdTime=1553526188905) is a link to our Teams conversation

## @ Mentions
@mjhenkes @emilyrohrbough

**Comment by nramamurth** [comment]
@mjhenkes @emilyrohrbough @ryanthemanuel Will the CI builds adapt the new ENV variable going forward? If yes, then I'd rather do https://github.com/cerner/terra-toolkit/commit/482900a15ffbe819f6a8bc9fb1c685ffbc0de14c so the test script in CI could explicitly set the `WDIO_BAIL` to 1 for CI. 

If not and if it is a non-passive change then something like the following snippet should do, me thinks.

```
bail: ci ? 1 : Number(process.env.WDIO_BAIL) || 0;
mochaOpts: {
   ...
   bail: ci || Boolean(process.env.WDIO_BAIL),
}
```

I was also wondering if the consumer should be restricted to have the limit as 1 failure per run or be free to configure whichever the number they prefer just like how the WebdriverIO<sup>[1]</sup> dictates. 

Let me know your thoughts. On a different note, how and where are the ENV variables `TRAVIS` and `CI` configured? 🧐

[1] https://webdriver.io/docs/options.html#bail

**Comment by ryanthemanuel** [comment]
I think we would want bail to be 1 if Travis, CI or the new variable is set.  CI and Travis gets set by the Travis build system in open source. CI gets set by Jenkins. Having an additional variable will allow us to set bail independently of CI (I.e. when running locally).

**Comment by nramamurth** [comment]
@ryanthemanuel I see what you are saying but in that case, I'd like to understand the rationale behind limiting it to be either 0 or 1. 

I was leaning more towards making the new variable flexible so that the consumers need not be restricted to have it limited to either 1  or 0 (they could set it to a value > 1 if they feel like because WebdriverIO allows it) and the Travis build system and Jenkins can _explicitly_ set it to 1 - that way I could completely remove the current `bail` logic<sup>[1][2]</sup> that is tied to `TRAVIS` and `CI` variables. 

Default being 0.

[1] https://github.com/cerner/terra-toolkit/blob/master/config/wdio/wdio.conf.js#L68
[2] https://github.com/cerner/terra-toolkit/blob/master/config/wdio/wdio.conf.js#L35

@mjhenkes Any thoughts?

**Comment by mjhenkes** [comment]
Lets keep this simple. One ENV that is true or false which either enables bail behavior unless your're in ci and it's ignored.

```javascript
const ci = process.env.TRAVIS || process.env.CI;
const bail = process.env.BAIL || ci;

...

bail: bail ? 1 : 0,

...

mochaOpts: {
    ui: 'bdd',
    timeout: 20000,
    bail,
  },
```
