### ISSUE TITLE
Evaluate css-loader v3 update

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-toolkit#300]
# Feature Request

## Description
css-loader v3 was just recently released. Need to evaluate it and see if we can update it in terra-toolkit as a passive update.

https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#300-2019-06-11

**Comment by emilyrohrbough** [comment]
Changes would be similar to:
```diff
{
    loader: 'css-loader',
    options: {
-       modules: 'global',
+       modules: {
+            mode: 'global',
+            localIdentName: '[name]__[local]___[hash:base64:5]',
+       }
        sourceMap: true,
         importLoaders: 2,
-       localIdentName: '[name]__[local]___[hash:base64:5]',
    },
}
  ```

**Comment by avinashg1994** [comment]
@bjankord , @emilyrohrbough 
I made the necessary changes and upgraded the version of css-loader to v3.2.0 as seen here https://github.com/cerner/terra-toolkit/compare/issue-300-css-loader-update.

Also, I verified these changes in Terra-Core, Terra-Clinical and Terra-UI without any issues.
While verifying with Terra-Framework, one of the wdio for Application Name was failing due to the delay in the icon loading., but this can be easily fixed by adding "browser.waitForVisible".

The main issue i am currently facing is when i verified with Terra-Dev-Site, i get the following error while running wdios and starting the local server: 
<img width="1198" alt="Screenshot 2019-09-11 at 6 29 19 PM" src="https://user-images.githubusercontent.com/50138162/64699868-587fea00-d4c3-11e9-9a3b-61d6013d177f.png">
I was not able to figure out where this error is originating from.
How do i go about resolving the above dev-site error?

**Comment by avinashg1994** [comment]
> @bjankord , @emilyrohrbough
> I made the necessary changes and upgraded the version of css-loader to v3.2.0 as seen here https://github.com/cerner/terra-toolkit/compare/issue-300-css-loader-update.
> 
> Also, I verified these changes in Terra-Core, Terra-Clinical and Terra-UI without any issues.
> While verifying with Terra-Framework, one of the wdio for Application Name was failing due to the delay in the icon loading., but this can be easily fixed by adding "browser.waitForVisible".
> 
> The main issue i am currently facing is when i verified with Terra-Dev-Site, i get the following error while running wdios and starting the local server:
> <img alt="Screenshot 2019-09-11 at 6 29 19 PM" width="1198" src="https://user-images.githubusercontent.com/50138162/64699868-587fea00-d4c3-11e9-9a3b-61d6013d177f.png">
> I was not able to figure out where this error is originating from.
> How do i go about resolving the above dev-site error?

Issue resolved as explained here : https://github.com/cerner/terra-toolkit/pull/338#issuecomment-532531946
