### ISSUE TITLE
Include 'module' in webpack mainFields

### ISSUE THREAD

**Issue by austin20XX** [cerner/terra-toolkit#591]
# Feature Request

## Description
Similarly to how 'browser' was [recently added](https://github.com/cerner/terra-toolkit/pull/536) to the resolve.mainFields, I would like to request 'module' be added in between so that the order is ['browser','module','main'].

## Additional Context / Screenshots
My team is experiencing a breaking issue in IE11 when importing the [uuid package](https://github.com/uuidjs/uuid) versions 8.3.0 or greater, as we see the syntax error `Expected ')'`. Based on the additional context section of [this](https://github.com/cerner/terra-toolkit/issues/522) feature request, it looks the 'browser' mainField was added for similar compatibility concerns.

Here are some threads with information regarding the issue and where I pulled the suggested solution from:
https://github.com/uuidjs/uuid/issues/516
https://github.com/uuidjs/uuid/issues/551

I modified my local terra webpack config to have the order ['browser','module','main'] and can confirm it did resolve the issue

**Comment by ryanthemanuel** [comment]
Hi @austinmack. We ran into problems with 'module' in the list of mainFields as a lot of projects have es6 code in those modules and they thus aren't babeled like they need to be for the browsers that we support. This *is* something you guys could override if you don't have that requirement.

**Comment by StephenEsser** [comment]
Related specifically to the `uuid` dependency; our projects are currently using version ^3.4.0 due to later versions of uuid dropping support for IE10. This version of uuid sounds really out of date, but if you look at the releases and tags it's only a handful of release behind and includes the majority of the uuid strategies:

https://github.com/uuidjs/uuid/tags
https://github.com/uuidjs/uuid/releases

If your project needs to support IE10 you may also need to drop down to ^3.4.0, but if not the webpack change or solutions posted on those threads might be better suited
